---
name: Run Updates on Terminal Servers then wait 7 mins
  hosts: 10.250.80.223
  connection: winrm

  tasks:
    win_updates:
      category_names:
        - Application
        - CriticalUpdates
        - DefinitionUpdates
        - SecurityUpdates
        - Updates
    reboot: yes
    reboot_timeout: 300
